### ISSUE TITLE
Mac環境にてエラー

### ISSUE THREAD

**Issue by conao3** [aki2o/emacs-vbasense#1]
visual-basic-modeを有効にした状態で.basファイルを開きましたが、補完が有効にならないため、「vbasense-setup-current-buffer」を実行したところ、次のエラーが出て有効になりませんでした。

Making completion list...
yaxception-throw-custom-err: [VBASense] Failed setup current buffer : /bin/bash: cmd.exe: command not found

cmd.exeとはWindowsのコマンドプロンプトかと想像しますが、Macは動作対象外なのでしょうか？

**Comment by aki2o** [comment]
連絡遅くなってすいませんmm
Macでの動作は想定してないですね...　これ使ってたのは、WindowsXP、Excel2003の環境です。
今は、自分もWindows持ってなくて、Windowsですら動作するのか不明...

Macに詳しくないんですが、同梱されてるchkTLI.batが実行できたり、DLLが登録できる必要があります。
cmd.exeはchkTLI.batを実行するのに指定してますが、 `cmd.exe /c chkTLI.bat` と同等のことができるなら、必要ないかも。

お役にたてずすいません。
自分では結構がんばって作って、実際VBAEditorと同等なくらいの使い勝手だったんですけどね...

**Comment by conao3** [comment]
コメントありがとうございます。こちらも(ry

バッチファイルを実行する必要があるのでしたら、macでは難しそうですね、、、
mac版のVBEが使いづらすぎたので検討していたのです。
また進展ありましたらpushしていただけると幸いです。
ありがとうございました。
